toggl_report/toggl_report/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('toggl_report_app/', include('toggl_report_app.urls')),
    path('admin/', admin.site.urls),
]

toggl_report/toggl_report_app/urls.py
from django.urls import path

from . import views

app_name = 'toggl_report_app'
urlpatterns = [
    path('', views.UserView.as_view(), name='user_view'),
    path('<str:pk>/daily_report/', views.DailyView.as_view(), name='daily_report'),
    path('<str:user_id>/daily_report/<str:date>/', views.daily_view, name='daily_report_view'),
    path('<str:user_id>/daily_report/<str:date>/circle_graph', views.showCircleGraph, name='show_circle_graph'),
    ]

toggl_report/toggl_report_app/models.py
from django.db import models

# Create your models here.

class TogglUser(models.Model):
    user_id = models.CharField(primary_key = True, max_length = 20)
    api_token = models.CharField(default = '', max_length = 100)
    mail = models.CharField(default = '', max_length = 100)

    def __str__(self):
        return self.user_id

class SelectedUser(models.Model):
    user_id = models.CharField(primary_key = True, max_length = 20)

    def __str__(self):
        return self.user_id

toggl_report/toggl_report_app/views.py
import requests
from requests.auth import HTTPBasicAuth
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.views import generic
from django.utils import timezone
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import japanize_matplotlib #Macでの日本語の対応
import io

from .models import TogglUser

class UserView(generic.ListView):
    template_name = 'toggl_report_app/index.html'
    context_object_name = 'user_select'

    def get_queryset(self):
        return TogglUser.objects.order_by('user_id')

class DailyView(generic.DetailView):
    template_name = 'toggl_report_app/daily_report.html'
    model = TogglUser
    context_object_name = 'toggl_user'
    today = "{0:%Y-%m-%d}".format(timezone.now())

    def render_to_response(self, context, **response_kwargs):
        return HttpResponseRedirect(reverse('toggl_report_app:daily_report_view', args = (context['toggl_user'].user_id, self.today, )))

    def get_queryset(self):
        return TogglUser.objects.filter()

def daily_view(request, user_id, date):
    user_info = get_object_or_404(TogglUser, pk = user_id)
    result = requests.get('https://api.track.toggl.com/api/v8/workspaces', auth = (user_info.api_token, 'api_token'))
    data = result.json()
    Data = data[0]
    params = {
        'user_agent': user_info.mail,
        'workspace_id': Data['id'],
        'since': date,
        'until': date,
    }
    r = requests.get('https://api.track.toggl.com/reports/api/v2/details',
                     auth=HTTPBasicAuth(user_info.api_token, 'api_token'),
                     params=params)
    json_r = r.json()
    context = {'workspace_id' : Data['id'], 'report_json' : json_r['data'], 'date': date, 'user_id': user_id}

    return render(request, 'toggl_report_app/daily_report.html', context)

def plt2png():
    buf = io.BytesIO()
    plt.savefig(buf, format='png', dpi=200)
    png_data = buf.getvalue()
    buf.close()
    return png_data

def getTogglData(user_id, date):
    user_info = get_object_or_404(TogglUser, pk = user_id)
    result = requests.get('https://api.track.toggl.com/api/v8/workspaces', auth = (user_info.api_token, 'api_token'))
    data = result.json()
    Data = data[0]
    context = {'workspace_id' : Data['id']}
    params = {
        'user_agent': user_info.mail,
        'workspace_id': Data['id'],
        'since': date,
        'until': date,
    }
    r = requests.get('https://api.track.toggl.com/reports/api/v2/details',
                     auth=HTTPBasicAuth(user_info.api_token, 'api_token'),
                     params=params)
    json_r = r.json()
    return json_r['data']

def showCircleGraph(request, user_id, date):
    toggl_data = getTogglData(user_id, date)
    labels = []
    sizes = []
    for tdata in toggl_data:
        labels.append(tdata['description'])
        sizes.append(tdata['dur'])

    fig, ax = plt.subplots()
    patches, texts, autotexts = ax.pie(sizes, labels=labels, autopct='%1.1f%%',
                                       shadow=True, startangle=90, labeldistance=0.7, pctdistance=0.5, wedgeprops={'linewidth': 1, 'edgecolor':"0.8"})
    ax.axis('equal') # 面積比=割合
    plt.rcParams['font.family'] = 'MS Gothic'
    plt.setp(autotexts, size=12)
    png_data = plt2png()
    plt.cla()
    response = HttpResponse(png_data, content_type='image/png')
    return response

toggl_report/toggl_report_app/templates/toggl_report_app/base.html
<!doctype html>
<html class="no-js">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
        <!-- jQuery -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        {% block head %}
        {% endblock %}
    </head>
<body>
    <div class="row">
        <div class="columns large-2">
            {% block left-body %}
            {% endblock %}
        </div>
        <div class="columns large-10">
            {% block body %}
            {% endblock %}
        </div>
    </div>
</body>
</html>

toggl_report/toggl_report_app/templates/toggl_report_app/daily_report.html
{% extends "./base.html" %}
{% block head %}
    {% load static %}
{% endblock %}
{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-3">
                <div class="cls_calendar_panel" id="id_calendar_panel">
                    <span id="prev_month"><-</span><span id="id_year"></span>年 <span id="id_month"></span>月<span id="next_month">-></span>
                    
                    <table class="calendar">
                        <thead>
                            <tr>
                                <th>月</th>
                                <th>火</th>
                                <th>水</th>
                                <th>木</th>
                                <th>金</th>
                                <th>土</th>
                                <th>日</th>
                            </tr>
                        </thead>
                        <tbody id="id_calendar_body">
                        </tbody>
                    </table>
                </div>
                <button class="btn btn-outline-secondary" type="submit">CHANGE USER</button>
                <button class="btn btn-primary" type="submit">LOAD</button>
            </div>
            <div class="col-9">
                <img src="{% url 'toggl_report_app:show_circle_graph' user_id date%}" width="700px" height="550px" alt = "">
            </div>
        </div>
    </div>
    
    <script type="text/javascript" src="{% static 'toggl_report_app/calendar.js' %}"></script>
    <div id="today" class="hidden">{{ date }}</div>
{% endblock %}

toggl_report/toggl_report_app/templates/toggl_report_app/index.html
{% extends "./base.html" %}

{% block body %}
    {% if user_select %}
        <ui>
            {% for user_id in user_select %}
                <li>
                    <a href="{% url 'toggl_report_app:daily_report' user_id %}"> {{user_id}} </a>
                </li>
            {% endfor %}
        </ui>
    {% else %}
        <p> No toggl_report_app user. </p>
    {% endif %}
{% endblock %}